#!/usr/bin/env php
<?php

use Composer\Autoload\ClassLoader;
use Modera\Module\Console\Application;

//umask(0000);
set_time_limit(0);

/**
 * @var $loader ClassLoader
 */
$loader = require_once __DIR__ . '/vendor/autoload.php';

$app = new Application();
$app->run();
